---
title: "Wrap up and clean up"
description: "What needs to be done as the project draws to a close."
---
  
Cleaning your project is an equally important step as the modelling and analysis. Leaving a messy project folder and code can lead to difficulties later down the line. It is important that you dedicate enough time to completing this step. Also, remember to treat it as a serious and worthwhile endeavour as it can come in handy in the future. 

## General tips for cleaning your project 


If you are using Git remember to work with the mindset that everything committed could be made public. Small and precise commits will make the project clean up easier to complete.

Even if the code base will not be made public, take the time to clean it up and make sure all development branches are committed to main or deleted. Streamlining the codebase is crucial. Be sure to archive old scripts that are no longer required. For the remaining scripts take the time to simplify and document the code. If you create a shiny dashboard as part of the project then your code should already be structured well. If it isn’t consider separating data, scripts and output into separate sub-directories. Remember to check the DALL GitHub page to look up other projects for inspiration. 

If you have written custom functions it is a good idea to place these into a separate functions script which can then be called later in the project. Be sure to document the functions making it clear what the expected input structure should look like and what each of the parameters correspond to. It is also important to state what the output corresponds to. Including a simple example of how the function works can also be useful but is not mandatory.

If you intend to re-run the code in the future, consider creating a config or preamble script. The config script should contain all the key parameters and filters used in the project. For example, if you are filtering by a date range you can define this in the config file and reference it throughout the project. This will speed up future work as only a single value needs editing before the code needs re running.

Cleaning code can be a subjective process. Remember to ask your critical friend for advice if you aren’t sure. When writing code in R a lot of DALL users like to use tidyverse packages. These packages offer direct querying with the database whilst offering a degree of readability. We should always try and find a balance between performance and readability. Code should perform well and run quickly but also be understood by colleagues. It should be noted that you are not constrained to use tidyverse packages. But keeping in mind readability with well commented code will improve your project.

If you have key base tables created within DALP make sure these are made available to the wider team. That way if you are away on annual leave or unavailable they are not lost. Often the key tables are moved to the DALL_REF schema. At the end of the project make sure to remove any tables that you have created. This includes permanent and temporary tables. Once a project concludes you shouldn’t have access to the data anymore, especially if it has personal information included.


