---
title: "Production"
description: "Developing, maintaining and running Reproducible Analytical Pipelines (RAPs)"
---

All of our Official Statistics are produced using [Reproducible Analytical Pipelines (RAPs)](https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/){target="_blank"}. RAPs are automated statistical and analytical processes that incorporate elements of software engineering best practice to ensure that pipelines are reproducible, auditable, efficient, and high quality. 

This guidance is not intended to give details on how to develop a RAP project. It assumes that you have worked with RAP before and know the basic principles and processes. If you are not familiar with RAP then you can find out more from:

* the [Quality Assurance of Code for Analysis and Research book](https://best-practice-and-impact.github.io/qa-of-code-guidance/intro.html){target="_blank"} created by the Analysis Standards and Pipelines team at the Office for National Statistics (ONS)
* NHS Digital's [RAP community of practice](https://nhsdigital.github.io/rap-community-of-practice/){target="_blank"}
* our own RAP guidance that is under development

## RAP
Our publications are supported by a collection of core R packages that have been developed and maintained by the Official Statistics team. Each publication has a pipeline repository that is ran to produce the publication outputs. A pipeline repository will look like:

```
pipeline
|-config.yml
|
|-pipeline.R
|
|-data
|-outputs
|-R
|-

```
