## Accessibility statement for NHSBSA Data Science Playbook

This accessibility statement applies to the NHSBSA Data Science Playbook website. 

This website is run by the NHS Business Services Authority (NHSBSA). We want as many people as possible to be able to use this website. For example, that means you should be able to:  
  
- zoom in up to 400% without the text spilling off the screen
- listen to most of the website using a screen reader (including the most recent version of NVDA)
- navigate most of the website using just a keyboard or speech recognition software (Dragon) 
- change colours, contrast levels and fonts using browser or device settings

We’ve also made the website text as simple as possible to understand.

[AbilityNet has advice on making your device easier to use](https://mcmw.abilitynet.org.uk/) if you have a disability.

### How accessible this website is

We know some parts of this website are not fully accessible, as: 
  
- navigation by tabbing does not always follow a left-to-right, top-to-bottom visual order
- zooming can only be done to a limited extent due to content becoming unviewable 
- the report has links to external PDF or Excel documents and websites which may have accessibility issues

### How to request content in an accessible format

If you need information on this website in a different format such as accessible PDF, large print, easy read, audio recording or braille, you can contact us by:
  
Email: [accessibility@nhsbsa.nhs.uk](mailto:accessibility@nhsbsa.nhs.uk) 

We’ll consider your request and get back to you in 5 working days.

This email address is only for accessibility queries. It is not for technical queries or IT problems. If you have a query that is not about accessibility, go to the ‘Contact us’ section of this page.

### Reporting accessibility problems with this website

We’re always looking to improve the accessibility of this website. If you find any problems that are not listed on this page or think we’re not meeting accessibility requirements, you can contact us by:
  
  Email: [accessibility@nhsbsa.nhs.uk](mailto:accessibility@nhsbsa.nhs.uk) 

This email address is only for accessibility queries. It is not for technical queries or IT problems. If you have a query that is not about accessibility, go to the ‘Contact us’ section of this page.

### Contact us

For all queries not accessibility related, you can contact us by:
  
Email: [dall@nhsbsa.nhs.uk](mailto:dall@nhsbsa.nhs.uk)

### Enforcement procedure

The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’). 

If you’re not happy with how we respond to your complaint, [contact the Equality Advisory and Support Service (EASS)](https://www.equalityadvisoryservice.com/).

### Technical information about this website’s accessibility 

The NHSBSA is committed to making its website accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.

#### Compliance status 

This website is partially compliant with the [Web Content Accessibility Guidelines version 2.2](https://www.w3.org/TR/WCAG22/) AA standard, due to the non-compliances listed below.

### Non-accessible content 

The content listed below is non-accessible for the following reasons.

#### Non-compliance with the accessibility regulations

Navigation by tabbing does not always follow a left-to-right, top-to-bottom visual order. This fails WCAG 2.2 success criterion 2.4.3 (Focus Order).

Zooming can only be done to a limited extent due to content becoming unviewable. This fails WCAG 2.2 success criterion 1.4.10 (Reflow).

The report has links to external PDF or Excel documents and websites which may have accessibility issues. This fails WCAG 2.2 success criteria 1.1.1 (Non-text Content), 1.3.1 (Info and Relationships) and 4.1.2 (Name, role, value).

We plan to fix these issues. When we publish new content, we’ll make sure it meets accessibility standards.

### What we’re doing to improve accessibility 

We’re committed to making sure this website is compliant to WCAG 2.2 ‘AA’ standard.

Our accessibility compliance statement will be reviewed regularly. Every newly released website will be designed, built, and tested to meet ‘AA’ standards by default.

### Preparation of this accessibility statement

This statement was originally prepared on 14 October 2023. It was last reviewed on 18 September 2024.

This website was last tested on 14 October 2024 against the WCAG 2.2 AA standard. 

The test was carried out by the NHSBSA test and development teams. The most viewed pages were tested using automated testing tools by our website team. A further audit of the website was carried out to the WCAG 2.2 AA standard.

We tested all the website screens to meet ‘AA’ WCAG 2.2 standards, using manual and automated tests.

We run each webpage through automated Wave, Lighthouse and Axe accessibility tools then manually test with screen readers (NVDA) and standards checklists.
We run representative user journey tests through speech recognition software (Dragon).

These checklists contain standards that have been compiled using WCAG, the NHS service manual and the Government Digital Service (GDS) guidance.
