---
title: "Analysis"
description: "Analysis loop - prepare data, analyse it and review until outputs in problem definition are finalised."
title-block-banner: true
listing: 
  type: grid
  contents: analysis-steps
  sort: "title"
---

## Data preparation

The goal of this step is to end up with one or more base tables on which analysis is then conducted. The base tables should include any data relevant, or possibly relevant, to the initiative. Data preparation may be iterative, as the analysis becomes refined with frequent feedback from stakeholders.

## Analysis and modelling

In this step we turn data into insights. This could involve a plethora of data science techniques from statistics to machine learning. The choice of which techniques to use will depend on the desired outputs of the initiative and what the data available allows. The problem definition should be used to steer the analysis towards delivery of the agreed outputs.

## Output artifacts

The expected outputs of an initiative will have been agreed in the problem definition. These will range from written reports, summary slide decks, data sets and applications such as dashboards or interactive reports. Getting frequent feedback is important, as it helps to prevent drift from the problem definition and allows more people to spot problems as early as possible. ?There are general guidelines that apply across most types of output.  

## Team review

Frequent reviews of the work give a chance to pick up on any issues before asking third parties to look at it. An important component of this is code review. With the mindset that the code may become public, put yourself in the shoes of someone coming across the code and wanting to both understand it and then reuse it. This means keeping in mind the principles of [Reproducible Analytical Pipelines (RAP)](RAP_playbook?), which benefits others coming across the code in future, but also the team themselves while continuing to work on it.

Test driven development: Write the tests before the code?  
If scope changes account for additional time later in the projects  
Ideally do accessibility testing upfront or as you go so you don't have to change loads of stuff  

## Critical friend review

The critical friend is an integral part of the team. They serve as someone to bounce ideas off, offer advice and act as a another pair of eyes and ears that may pick up up on something unnoticed by the rest of the team. So keep them in the loop as much as possible by asking them to review things before taking anything to the customer of the initiative.

Ideally create an issue and PR combination and have them reviewed as you go by the critical friend, rather than a massive check at the end  
Can be an element of waiting around while waiting for review  
Can be make a branch on another branch to continue while waiting  
Get them involved as early as possible  
Keep them in the loop throughout, rather than right at the end  
They should refer to the PD and make sure everything is correct and on track  
Potentially they should just be on the output and make sure it looks good, any ideas?  
Don't accept suggestions just to be "nice". Similarly, be confident in making suggestions and don't worry about offending people! This is part of the value a critical friend should bring to a project.  
If reviewing code make sure to give the critical friend small but frequent  bits of code to review  
Find a critical friend, who has done the coding before or content or both  
Bring the critical friend along for a "second set of ears"  
Hard to find critical friend, conscious everyone is busy  
Table or JIRA to see what everyone is working on, if they're already a critical friend?  
Involve your critical friends from the beginning - they may notice things you missed  
Give your critical friend notice that stuff to review will be coming their way  
Don't be afraid to voice your opinion/challenge more senior members of the team  

## Customer review

Before asking the customer to review and feedback on the work, ensure that whichever output they are looking at is either complete according to the problem definition, or for work in progress that you have made it clear what points on the problem definition are (or are not) being covered so far. Use the feedback to help steer things back on course if necessary. Something that can occur is the customer now asking for something different, or entirely new. This should be handled with care, as over-committing can backfire. In such cases it may be better to propose a future phase of work for any additional outputs requested. 
